modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="breadmod"
version="${version}"
displayName="Breadmod"
authors="bbbreaddd"
description='''Improves recipe handling and compatibility between EMI, JEI, Refined Storage, Mystical Agriculture, and other mods.'''

[[mixins]]
config="breadmod.mixins.json"

[[dependencies.breadmod]]
modId="emi"
mandatory=true
versionRange="[1.1.20,1.2.0)"
ordering="AFTER"
side="CLIENT"

[[dependencies.breadmod]]
modId="jei"
mandatory=true
versionRange="[15.20.0,16.0.0)"
ordering="AFTER"
side="CLIENT"

[[dependencies.breadmod]]
modId="refinedstorage"
mandatory=true
versionRange="[1.12.0,1.13.0)"
ordering="AFTER"
side="CLIENT"
